<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Add Consumer Credentials</title>
</head>
<body>
<div class="container">
    <form class="form-horizontal" action="http://deployer.loc/credentials-save/" method="post">
        <div class="control-group">
            <label class="control-label" for="inputEmail">Consumer Public Key</label>
            <div class="controls">
                <input type="text" id="consumerPublicKey" name="consumerPublicKey" value="" placeholder="Consumer Public Key">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputPassword">Consumer Secret Key</label>
            <div class="controls">
                <input type="text" id="consumerSecretKey" name="consumerSecretKey" value="" placeholder="Consumer Secret Key">
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="control-label" for="inputEmail">Consumer Code</label>
                <div class="controls">
                    <input type="text" id="consumerCode" name="consumerCode" value="" placeholder="Consumer Code">
                </div>
            </div>
        </div>
        <br>
        <input type="submit" value="Save" class="btn" </>
    </form>
</div>
</body>
</html>
